### ISSUE TITLE
Can mOS be used in conjunction with IPS, not IDS?

### ISSUE THREAD

**Issue by laybatin** [ndsl-kaist/mOS-networking-stack#19]
Can mOS be used in conjunction with IPS, not IDS?

I am building and testing an in-line environment. (http://www.ndsl.kaist.edu/mos_guide/_images/midstat_inline.png)

For example
If the HTTP data is 100 MB, the client's browser must be stopped for the time that the IPS will scan. After the IPS has been checked, it must be blocked or allowed.

is this possible?

In testing, when a packet is dropped using ```MOS_DROP```, the client does not receive an ACK and retransmission occurs.

Can we solve this?

**Comment by a-jamshed** [comment]
Hi @laybatin,

I am sorry I missed this message (GitHub never sent me the email notification for this issue). If I understand your question correctly, you want your middlebox to act as a TCP proxy. This means that the middlebox should not forward the client message to the destination server till it has scanned the entire message payload (that may span several packets). In the mean time, the proxy should send back ``ACK`` packets to the client so that  it does not experience "packet loss". Am I right? In other words, you don't even need to establish the connection (``SYN`` handshake) with the server if the IPS drops the packets.

Although, one can use mOS API to implement a tool that cover these requirements, I would suggest that you have a look at the [mTCP networking API](http://mos.kaist.edu/index_man.html) part of the library. A better way to construct this program will be to use mTCP end sockets for connection splicing features.
